# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    steps:
    # Steps represent a sequence of tasks that will be executed as part of the job
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: choco install winflexbison3
    - name: Check in Path
      run: win_flex --version
    - name: Make Build Directory
      run: mkdir -p build
    - name: Generate CMake Project
      run: (cd build && cmake ..)
    - name: Build Project
      run: cmake --build build
